name: BATS Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install BATS
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: Run BATS tests
        env:
          TERM: xterm
        run: script -q -c "bats --formatter pretty --recursive test" /dev/null
